/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author pedrovazquezg
 */
public class VentanaGanador extends javax.swing.JDialog {
    private String usuario;

    /**
     * Creates new form VentanaGanador
     */
    public VentanaGanador(java.awt.Frame parent, boolean modal, String usuario) {
        super(parent, modal);
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaFuerza = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        botonAgain = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        etiquetaFelicitacion = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("¡Felicidades, ganaste!");

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaFuerza.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        etiquetaFuerza.setForeground(new java.awt.Color(255, 204, 51));
        etiquetaFuerza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFuerza.setText("LA FUERZA TE ACOMPAÑA");
        panel.add(etiquetaFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 620, -1));

        etiquetaNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 204, 51));
        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombre.setText(usuario + ", ");
        panel.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 620, -1));

        botonAgain.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        botonAgain.setText("Jugar de nuevo");
        botonAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgainActionPerformed(evt);
            }
        });
        panel.add(botonAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        botonSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panel.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        etiquetaFelicitacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        etiquetaFelicitacion.setForeground(new java.awt.Color(255, 204, 0));
        etiquetaFelicitacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaFelicitacion.setText("¡Felicidades, Ganaste! ");
        panel.add(etiquetaFelicitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 620, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgainActionPerformed
        dispose();
    }//GEN-LAST:event_botonAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGanador dialog = new VentanaGanador(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgain;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaFelicitacion;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaFuerza;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
