/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pedrovazquezg
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaRegistroAtletas = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaEdad = new javax.swing.JLabel();
        etiquetaPeso = new javax.swing.JLabel();
        etiquetaEstatura = new javax.swing.JLabel();
        boxNombre = new javax.swing.JTextField();
        boxEdad = new javax.swing.JTextField();
        boxPeso = new javax.swing.JTextField();
        boxEstatura = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuMostrarAtletas = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Atletas");

        panel.setBackground(new java.awt.Color(51, 51, 51));

        etiquetaRegistroAtletas.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 24)); // NOI18N
        etiquetaRegistroAtletas.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaRegistroAtletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaRegistroAtletas.setText("Registro de atletas");

        etiquetaNombre.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 14)); // NOI18N
        etiquetaNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaNombre.setText("Nombre:");

        etiquetaEdad.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 14)); // NOI18N
        etiquetaEdad.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaEdad.setText("Edad:");

        etiquetaPeso.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 14)); // NOI18N
        etiquetaPeso.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaPeso.setText("Peso (Kg):");

        etiquetaEstatura.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 14)); // NOI18N
        etiquetaEstatura.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaEstatura.setText("Estatura (cm):");

        boxNombre.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 13)); // NOI18N

        boxEdad.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 13)); // NOI18N

        boxPeso.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 13)); // NOI18N

        boxEstatura.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 13)); // NOI18N

        botonRegistrar.setBackground(new java.awt.Color(255, 153, 0));
        botonRegistrar.setFont(new java.awt.Font(".AppleSystemUIFontMonospaced", 0, 14)); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaRegistroAtletas, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRegistrar)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(etiquetaEstatura)
                            .addGap(18, 18, 18)
                            .addComponent(boxEstatura, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(etiquetaEdad)
                                .addComponent(etiquetaNombre)
                                .addComponent(etiquetaPeso))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boxNombre)
                                .addComponent(boxEdad)
                                .addComponent(boxPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(etiquetaRegistroAtletas)
                .addGap(47, 47, 47)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(boxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEdad)
                    .addComponent(boxEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPeso)
                    .addComponent(boxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEstatura)
                    .addComponent(boxEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(botonRegistrar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        menu.setText("File");
        menu.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        menuMostrarAtletas.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        menuMostrarAtletas.setText("Mostrar atletas");
        menuMostrarAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMostrarAtletasActionPerformed(evt);
            }
        });
        menu.add(menuMostrarAtletas);
        menu.add(separador);

        menuSalir.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menu.add(menuSalir);

        barraMenu.add(menu);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String nombre; 
        int edad;
        double peso;
        int estatura;
        
        nombre = boxNombre.getText();
        edad = Integer.parseInt(boxEdad.getText());
        peso = Double.parseDouble(boxPeso.getText());
        estatura = Integer.parseInt(boxEstatura.getText());
        
        Atleta atleta = new Atleta(nombre, edad, peso, estatura);
        
        escribirBinario(atleta);
        
        boxNombre.setText("");
        boxEdad.setText("");
        boxPeso.setText("");
        boxEstatura.setText("");
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void menuMostrarAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMostrarAtletasActionPerformed
        VentanaRegistro registro = new VentanaRegistro(this, true);
        registro.setVisible(true);
    }//GEN-LAST:event_menuMostrarAtletasActionPerformed

    private void escribirBinario(Atleta atleta) {
        try {
            FileOutputStream archivo = new FileOutputStream("registroAtletas.bin", true);
            aBin escribir = new aBin(archivo);
            escribir.writeObject(atleta);
            escribir.close();
        } catch (FileNotFoundException ex) {
            System.err.println("Error. " + ex);
        } catch (IOException ex) {
            System.err.println("Error. " + ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField boxEdad;
    private javax.swing.JTextField boxEstatura;
    private javax.swing.JTextField boxNombre;
    private javax.swing.JTextField boxPeso;
    private javax.swing.JLabel etiquetaEdad;
    private javax.swing.JLabel etiquetaEstatura;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPeso;
    private javax.swing.JLabel etiquetaRegistroAtletas;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuMostrarAtletas;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panel;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
